# Generated by Django 2.2.7 on 2021-04-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210423_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blo',
        ),
    ]
