# Generated by Django 2.2.7 on 2021-04-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210410_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='Specialist_doctor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='Waiting_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='address_detail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='numper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='working_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
