# Generated by Django 2.2.7 on 2021-04-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210411_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
