# Generated by Django 2.2.7 on 2021-04-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profiel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
