# Generated by Django 2.2.7 on 2021-04-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210412_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='google',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='nationl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='tytr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
