# Generated by Django 2.2.7 on 2021-04-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210412_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiel',
            name='doctor_type',
            field=models.CharField(blank=True, choices=[('f', 'female'), ('m', 'male')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiel',
            name='timecreate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
