# Generated by Django 2.2.7 on 2021-04-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_pest_profiel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pest_profiel',
            old_name='Usr',
            new_name='pest_pro',
        ),
    ]
